// Macro generated from application: python
// By ROOT version 6.36.04 on 2026-02-14 10:35:50

#include "TStyle.h"

void Style_Mono() {
  // Add the saved style to the current ROOT session.

  delete gROOT->GetStyle("Modern");

  TStyle *tmpStyle = new TStyle("Modern", "Modern Style");
  tmpStyle->SetNdivisions(20506, "x");
  tmpStyle->SetNdivisions(20506, "y");
  tmpStyle->SetNdivisions(20506, "z");
  tmpStyle->SetAxisColor(1, "x");
  tmpStyle->SetAxisColor(1, "y");
  tmpStyle->SetAxisColor(1, "z");
  tmpStyle->SetLabelColor(1, "x");
  tmpStyle->SetLabelColor(1, "y");
  tmpStyle->SetLabelColor(1, "z");
  tmpStyle->SetLabelFont(112, "x");
  tmpStyle->SetLabelFont(112, "y");
  tmpStyle->SetLabelFont(112, "z");
  tmpStyle->SetLabelOffset(0, "x");
  tmpStyle->SetLabelOffset(0.01, "y");
  tmpStyle->SetLabelOffset(0.01, "z");
  tmpStyle->SetLabelSize(0.035, "x");
  tmpStyle->SetLabelSize(0.035, "y");
  tmpStyle->SetLabelSize(0.035, "z");
  tmpStyle->SetTickLength(0.035, "x");
  tmpStyle->SetTickLength(0.035, "y");
  tmpStyle->SetTickLength(0.035, "z");
  tmpStyle->SetTitleOffset(1, "x");
  tmpStyle->SetTitleOffset(1, "y");
  tmpStyle->SetTitleOffset(1, "z");
  tmpStyle->SetTitleSize(0.033, "x");
  tmpStyle->SetTitleSize(0.033, "y");
  tmpStyle->SetTitleSize(0.033, "z");
  tmpStyle->SetTitleColor(1, "x");
  tmpStyle->SetTitleColor(1, "y");
  tmpStyle->SetTitleColor(1, "z");
  tmpStyle->SetTitleFont(102, "x");
  tmpStyle->SetTitleFont(102, "y");
  tmpStyle->SetTitleFont(102, "z");
  tmpStyle->SetExponentOffset(0, 0, "x");
  tmpStyle->SetExponentOffset(0, 0, "y");
  tmpStyle->SetAxisMaxDigits(5);
  tmpStyle->SetBarWidth(1);
  tmpStyle->SetBarOffset(0);
  tmpStyle->SetDrawBorder(0);
  tmpStyle->SetOptLogx(1);
  tmpStyle->SetOptLogy(0);
  tmpStyle->SetOptLogz(0);
  tmpStyle->SetOptDate(0);
  tmpStyle->SetOptStat(0);
  tmpStyle->SetOptTitle(0);
  tmpStyle->SetOptFit(0);
  tmpStyle->SetNumberContours(20);
  tmpStyle->GetAttDate()->SetTextFont(102);
  tmpStyle->GetAttDate()->SetTextSize(0.025);
  tmpStyle->GetAttDate()->SetTextAngle(0);
  tmpStyle->GetAttDate()->SetTextAlign(11);
  tmpStyle->GetAttDate()->SetTextColor(1);
  tmpStyle->SetDateX(0.01);
  tmpStyle->SetDateY(0.01);
  tmpStyle->SetEndErrorSize(2);
  tmpStyle->SetErrorX(0.5);
  tmpStyle->SetFuncColor(2);
  tmpStyle->SetFuncStyle(1);
  tmpStyle->SetFuncWidth(3);
  tmpStyle->SetGridColor(0);
  tmpStyle->SetGridStyle(3);
  tmpStyle->SetGridWidth(2);
  tmpStyle->SetLegendBorderSize(2);
  tmpStyle->SetLegendFillColor(0);
  tmpStyle->SetLegendFillStyle(1001);
  tmpStyle->SetLegendFont(102);
  tmpStyle->SetLegendTextSize(0);
  tmpStyle->SetHatchesLineWidth(2);
  tmpStyle->SetHatchesSpacing(1);
  tmpStyle->SetFrameFillColor(0);
  tmpStyle->SetFrameLineColor(1);
  tmpStyle->SetFrameFillStyle(1001);
  tmpStyle->SetFrameLineStyle(1);
  tmpStyle->SetFrameLineWidth(2);
  tmpStyle->SetFrameBorderSize(1);
  tmpStyle->SetFrameBorderMode(1);
  tmpStyle->SetHistFillColor(0);
  tmpStyle->SetHistLineColor(1);
  tmpStyle->SetHistFillStyle(1001);
  tmpStyle->SetHistLineStyle(1);
  tmpStyle->SetHistLineWidth(2);
  tmpStyle->SetHistMinimumZero(kFALSE);
  tmpStyle->SetCanvasPreferGL(kFALSE);
  tmpStyle->SetCanvasColor(0);
  tmpStyle->SetCanvasBorderSize(2);
  tmpStyle->SetCanvasBorderMode(0);
  tmpStyle->SetCanvasDefH(500);
  tmpStyle->SetCanvasDefW(700);
  tmpStyle->SetCanvasDefX(10);
  tmpStyle->SetCanvasDefY(10);
  tmpStyle->SetPadColor(0);
  tmpStyle->SetPadBorderSize(2);
  tmpStyle->SetPadBorderMode(0);
  tmpStyle->SetPadBottomMargin(0.1);
  tmpStyle->SetPadTopMargin(0.1);
  tmpStyle->SetPadLeftMargin(0.1);
  tmpStyle->SetPadRightMargin(0.1);
  tmpStyle->SetPadGridX(kFALSE);
  tmpStyle->SetPadGridY(kFALSE);
  tmpStyle->SetPadTickX(0);
  tmpStyle->SetPadTickY(0);
  tmpStyle->SetOrthoCamera(kFALSE);
  tmpStyle->SetCandleWhiskerRange(1);
  tmpStyle->SetCandleBoxRange(0.5);
  tmpStyle->SetCandleScaled(kFALSE);
  tmpStyle->SetViolinScaled(kTRUE);
  tmpStyle->SetPaperSize(20, 26);
  tmpStyle->SetScreenFactor(1);
  tmpStyle->SetStatColor(0);
  tmpStyle->SetStatTextColor(1);
  tmpStyle->SetStatBorderSize(1);
  tmpStyle->SetStatFont(112);
  tmpStyle->SetStatFontSize(0);
  tmpStyle->SetStatStyle(1001);
  tmpStyle->SetStatFormat("6.4g");
  tmpStyle->SetStatX(0.98);
  tmpStyle->SetStatY(0.935);
  tmpStyle->SetStatW(0.2);
  tmpStyle->SetStatH(0.16);
  tmpStyle->SetStripDecimals(kTRUE);
  tmpStyle->SetTitleAlign(23);
  tmpStyle->SetTitleFillColor(0);
  tmpStyle->SetTitleTextColor(1);
  tmpStyle->SetTitleBorderSize(2);
  tmpStyle->SetTitleFont(102);
  tmpStyle->SetTitleFontSize(0.05);
  tmpStyle->SetTitleStyle(0);
  tmpStyle->SetTitleX(0.5);
  tmpStyle->SetTitleY(0.995);
  tmpStyle->SetTitleW(0);
  tmpStyle->SetTitleH(0);
  tmpStyle->SetLegoInnerR(0.5);

  TColor::SetPalette(57, nullptr);

  tmpStyle->SetLineStyleString(0, "");
  tmpStyle->SetLineStyleString(1, "   ");
  tmpStyle->SetLineStyleString(2, "  12 12");
  tmpStyle->SetLineStyleString(3, "  4 8");
  tmpStyle->SetLineStyleString(4, "  12 16 4 16");
  tmpStyle->SetLineStyleString(5, "  20 12 4 12");
  tmpStyle->SetLineStyleString(6, "  20 12 4 12 4 12 4 12");
  tmpStyle->SetLineStyleString(7, "  20 20");
  tmpStyle->SetLineStyleString(8, "  20 12 4 12 4 12");
  tmpStyle->SetLineStyleString(9, "  80 20");
  tmpStyle->SetLineStyleString(10, "  80 40 4 40");
  tmpStyle->SetLineStyleString(11, "   ");
  tmpStyle->SetLineStyleString(12, "   ");
  tmpStyle->SetLineStyleString(13, "   ");
  tmpStyle->SetLineStyleString(14, "   ");
  tmpStyle->SetLineStyleString(15, "   ");
  tmpStyle->SetLineStyleString(16, "   ");
  tmpStyle->SetLineStyleString(17, "   ");
  tmpStyle->SetLineStyleString(18, "   ");
  tmpStyle->SetLineStyleString(19, "   ");
  tmpStyle->SetLineStyleString(20, "   ");
  tmpStyle->SetLineStyleString(21, "   ");
  tmpStyle->SetLineStyleString(22, "   ");
  tmpStyle->SetLineStyleString(23, "   ");
  tmpStyle->SetLineStyleString(24, "   ");
  tmpStyle->SetLineStyleString(25, "   ");
  tmpStyle->SetLineStyleString(26, "   ");
  tmpStyle->SetLineStyleString(27, "   ");
  tmpStyle->SetLineStyleString(28, "   ");
  tmpStyle->SetLineStyleString(29, "   ");

  tmpStyle->SetHeaderPS("");
  tmpStyle->SetTitlePS("");
  tmpStyle->SetFitFormat("5.4g");
  tmpStyle->SetPaintTextFormat("g");
  tmpStyle->SetLineScalePS(3);
  tmpStyle->SetJoinLinePS(0);
  tmpStyle->SetCapLinePS(0);
  tmpStyle->SetColorModelPS(0);
  tmpStyle->SetTimeOffset(788918400);
  tmpStyle->SetLineColor(1);
  tmpStyle->SetLineStyle(1);
  tmpStyle->SetLineWidth(2);
  tmpStyle->SetFillColor(19);
  tmpStyle->SetFillStyle(1001);
  tmpStyle->SetMarkerColor(1);
  tmpStyle->SetMarkerStyle(1);
  tmpStyle->SetMarkerSize(1);
  tmpStyle->SetTextAlign(11);
  tmpStyle->SetTextColor(1);
  tmpStyle->SetTextFont(112);
  tmpStyle->SetTextSize(0.05);

  gROOT->SetStyle("Modern");
  gROOT->ForceStyle();
}
