
# =========================
# Inicializa o kernel
# =========================
/run/initialize

# =========================
# Abre OpenGL
# =========================
/vis/open OGL

# =========================
# Desenha a geometria
# =========================
/vis/drawVolume

# =========================
# Estilo
# =========================
/vis/viewer/set/style wireframe

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate 1000

/vis/scene/add/hits
# =========================
# Fundo
# =========================
#/vis/viewer/set/background white
#/process/had/rdm/verbose 2
/process/had/rdm/thresholdForVeryLongDecayTime 1e+12 s
# =========================
# Câmera
# =========================

