
# =========================
# Inicializa o kernel
# =========================
/run/initialize

# =========================
# Abre OpenGL
# =========================
/vis/open OGL

# =========================
# Desenha a geometria
# =========================
/vis/drawVolume

# =========================
# Estilo
# =========================
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineWidth 2

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate 1000

/vis/scene/add/hits
# =========================
# Fundo
# =========================
/vis/viewer/set/background white

# =========================
# Câmera
# =========================
/vis/viewer/set/viewpointThetaPhi 70 20
/vis/viewer/zoom 1.4
/vis/viewer/flush

# /run/beamOn 10
